name: gpt
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - python
  - pip
  - fastai==1.0.59
  - pytorch>=1.3
  - cuda100 
  - regex
  - langdetect
  - tensorboardX
  - cudatoolkit
  - tensorboard==1.15.0
  - tensorflow>=2
  - uvicorn
  - terraform
  - google-cloud-sdk
  - tar 
  - zstd
  - transformers==2.2.0
  - pip:
    - pyTelegramBotAPI
    - pysocks
    - tendo
    - schedule
    - fastapi>=0.41
    - youtokentome
    - requests
    - rupo
    - transitions
    - mezmorize
