name: gpt
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - python
  - pip
  - fastai 
  - pytorch>=1.2
  - cuda100 
  - regex
  - langdetect
  - tensorboardX
  - cudatoolkit
  - tensorboard>=1.14
  - tensorflow>=1.13
  - pip:
    - transformers
    - sentencepiece
    - pyTelegramBotAPI
    - pysocks
    - tendo
    - schedule